version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 633242779871.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t node-app .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to Amazon ECR...
      - docker tag node-app:latest 633242779871.dkr.ecr.us-east-1.amazonaws.com/node-app:latest
      - docker push 633242779871.dkr.ecr.us-east-1.amazonaws.com/node-app:latest

artifacts:
  files:
    - '**/*'
